bcgov/court-interpreter-scheduling

.github/workflows/deploy.yml, devops/Makefile, devops/openshift/api-deploy.yml, docker-compose.dev.yml, docker-compose.test.yml, frontend/.prettierrc, frontend/Dockerfile, frontend/src/index.tsx, frontend/src/keycloak.ts
=> deploy to PRD.

frontend/src/components/table/DirectoryTable.tsx
- sorting on column city when you click on header
=> add sorting on city

frontend/src/components/form/BookingsSearch.tsx, frontend/src/components/form/DirectorySearch.tsx, frontend/src/components/form/InterpreterSearch.tsx, frontend/src/components/table/InterpretersTable.tsx
- remove search location from all pages && add city to interpreter page
=> remove search location from all pages && add city to interpreter page

api/src/interpreter/entities/interpreter.entity.ts, api/src/interpreter/ro/interpreter.ro.ts, frontend/src/components/form/BookingModal.tsx, frontend/src/components/form/Range.tsx, frontend/src/components/table/DirectoryTable.tsx, frontend/src/components/table/InterpretersTable.tsx, frontend/src/css/App.css, frontend/src/views/Booking.tsx
I was able to cherry-pick by creating a new remote (the gov repo) and `checkout` using the `--track` flag!
https://www.elliotblackburn.com/cherry-pick-git-commit-across-repository/
=> Gov comments check

frontend/src/components/table/InterpreterSearchTable.tsx, frontend/src/util/sort.ts
Once a search on language has been made, use the level field to create the order for the language column
=> additional table utility method to sort the languages array by level

frontend/src/components/form/inputs/Interpreter.tsx
forgot to get this change in as well
=> add criminal record check field to interpreter inputs

api/src/interpreter/entities/interpreter.entity.ts
on interpreter entity for the booking relation
=> revert the SET NULL directive

frontend/src/components/table/InterpreterDirectoryTable.tsx
apply sorting functions to directory table: base function employed on whether or not a language has been searched for
=> reuse sorting functions on directory table for language and level

api/src/interpreter/interpreter.controller.ts, frontend/public/index.html
=> missed the businessPhone field

Makefile, docker-compose.yml, frontend/src/components/table/InterpreterDirectoryTable.tsx
----------------------------------------------------------------------------
1. Update UI
2. Add make cmd to run api locally with db
3. Update docker.compose to use env injection for keycloak items
=> [web][BCCIS-#119] Add active / inactive indicator on interpreter table/dir

api/src/common/decorator/query.decorator.ts, api/src/interpreter/dto/paginate-interpreter-query.dto.ts, api/src/interpreter/entities/interpreter.entity.ts, api/src/interpreter/interpreter.service.ts, frontend/src/components/form/DirectorySearch.tsx, frontend/src/components/form/inputs/Autocomplete.tsx, frontend/src/constants/interfaces.ts, frontend/src/contexts/InterpreterSearchContext.ts, frontend/src/views/InterpreterDirectory.tsx
------------------------------------------------------------------------------
1. Add new Active/Inactive options interpreter directory
2. Update Search DB query in API
-----
=> [frontend][api][SIM-#120] Implement Active/Inactive filter on Interpreter Dir

Makefile, api/src/database/factories/Interpreter.factory.ts, api/src/interpreter/dto/create-interpreter.dto.ts, api/src/interpreter/entities/interpreter.entity.ts, api/src/interpreter/interpreter.service.ts, api/src/migrations/1615237511821-UpdateInterPreterCRCColumns.ts
-----------------
1. Rename old field as comment (**criminal_record_check -> criminal_record_check_comment**) field to store free text info
2. Add new **criminal_record_check_date** field
3. Add IS_DATE function in db
4. Migrate existing field valid date field to new field
5. Update db entity
6. Update factory
N.B.
This is API part of [task](https://freshworks.atlassian.net/browse/BCCIS-121).
TODO:
1. Update Front end code
2. Remove legacy criminal_record_check_comment field
=> [api][BCCIS-#121] Updating CRC field of Interpreter table

api/src/interpreter/dto/create-interpreter.dto.ts, api/src/interpreter/entities/interpreter.entity.ts, api/src/interpreter/ro/interpreter.ro.ts, frontend/src/components/form/DirectorySearch.tsx, frontend/src/components/form/inputs/Autocomplete.tsx, frontend/src/components/form/inputs/Interpreter.tsx, frontend/src/components/form/schemas/interpreter-search.schema.ts, frontend/src/constants/interfaces.ts
-----
1. Add new date field
2. Update interface
3. Make existing legacy field optional if non date object present.
---
=> [api][frontend][BCCIS-#121] Front end change for CRC field 

api/.config/.env.example, api/src/app.controller.ts, api/src/common/decorator/flag.decorator.ts, api/src/common/interface/flag.ts, devops/openshift/api-deploy.yml, frontend/src/components/form/InterpreterSearch.tsx, frontend/src/components/layout/SubHeader.tsx, frontend/src/components/reusable/withFlag.tsx, frontend/src/index.tsx, frontend/src/util/localStorageUtil.ts
**Resolves:**
- Add feature flag
**Changes:**
1. **Backend:**
- adding `flag decorator` for easily scale in the future
2. **Frontend:**
- adding HOC `withFlag`
3. **DevOps:**
- adding two new env variables
**References:**
- [CSBISS-78](https://justice.gov.bc.ca/jira/browse/CSBISS-78)
=> [CSBISS-78] Feature flag

.github/workflows/deploy.yml, api/.config/.env.example, devops/Makefile, devops/openshift/api-deploy.yml
---------------
Add two env var DEPLOYMENT_ENV, DEPLOYMENT_ENV_HIDDEN_FLAG to all remote env
=> [devops][workflow] Add env variables

frontend/src/App.tsx, frontend/src/components/reusable/withFlag.tsx
**Resolves:**
- fix the frontend routing bug
**Changes:**
- adding flag to the route
**References:**
- [CSBISS-78](https://justice.gov.bc.ca/jira/browse/CSBISS-78)
=> hotfix-frontend-bug feature flag

api/src/booking/dto/create-booking.dto.ts, api/src/database/factories/Interpreter-language.factory.ts, api/src/database/seeds/1-create-language.seed.ts, frontend/src/components/form/inputs/Booking.tsx
-----------
1. Add data transformer to manage case sensetive language name
2. Update factory
=> [api][frontend][CSBISS-#83] ASL language interpreter booking issue

api/src/booking/dto/create-booking.dto.ts
**Problem**: Language is empty for newly created **_booking_** 
**Fix**: Problem with new value transformer in api
Context: [CSBISS-#83](https://justice.gov.bc.ca/jira/browse/CSBISS-83)
=> [api][CSBISS-#83] Fix booking with empty lang

frontend/src/index.tsx
=> fix TEST login issue

frontend/src/components/table/BookingsTable.tsx, frontend/src/hooks/axios.ts, frontend/src/index.tsx
just merge frontend code to backend branch
=> Export spreadsheet fe

frontend/src/index.tsx
=> hotfix - testing fail

frontend/src/hooks/axios.ts, frontend/src/index.tsx, frontend/src/keycloak.ts
- the reason is because `kcClient` is caching the `authUrl` when doing the `import`
=> fix TEST env redirect to wrong kc issue

api/src/booking/booking.service.ts, frontend/src/components/table/BookingsTable.tsx, frontend/src/hooks/useAlert.tsx
- add invoice value to `W5` and `F113`, so that it can show even without clicking "enable editing".
(and sorry, my excel is in the Chinese version, the yellow bar is "enable editing prompt".
- fix frontend alert issue.
=> Add Excel invoice

api/src/booking/booking.service.ts, api/src/utils/anonymisation.ts
- `555-555-5555` is not a valid CA number, that's why fail the validation.
- switch to faker phone number
- Another requirement from Graeme, change the format of the invoice.
***Refs***
- https://github.com/Marak/faker.js/wiki/Phone
=> [bug] update anonymous interpreter 400 issues

api/src/interpreter/dto/create-interpreter.dto.ts, api/src/utils/anonymisation.ts, frontend/src/components/form/BookingModal.tsx
two bugs
- update interpreter error
- create booking default language error
=> hotfix - update interpreters

api/src/booking/booking.module.ts, api/src/booking/booking.service.ts, api/src/booking/dto/create-booking.dto.ts, api/src/booking/dto/paginate-booking-query.dto.ts, api/src/booking/entities/booking.entity.ts, api/src/booking/ro/booking.ro.ts, api/src/database/database.module.ts, api/src/migrations/1618326410955-BookingLocation.ts, frontend/src/components/form/BookingModal.tsx, frontend/src/components/form/inputs/Booking.tsx, frontend/src/components/form/schemas/booking.schema.ts, frontend/src/constants/courtLocations.ts, frontend/src/constants/interfaces.ts
-------
1. Create FK ref in booking table
2. Update Booking dto
3. Update booking entity model
---
=> [api] Create relation between court location and booking entity

api/src/booking/booking.service.ts, frontend/src/components/form/BookingsSearch.tsx
------------
1. Add court location based search filter on booking
2. Fix location assignement issue for create or update booking
--
=> [api][frontend] Booking location filter

api/src/booking/booking.controller.ts, api/src/booking/booking.service.ts, api/src/booking/dto/create-booking.dto.ts, api/src/booking/entities/booking.entity.ts, api/src/booking/ro/booking.ro.ts, api/src/distance/distance.service.ts, api/src/interpreter/dto/paginate-interpreter-query.dto.ts, api/src/location/location.service.ts, frontend/src/components/form/BookingModal.tsx, frontend/src/components/form/InterpreterSearch.tsx, frontend/src/components/form/inputs/AutoCompleteField.tsx, frontend/src/components/form/inputs/Booking.tsx, frontend/src/components/form/inputs/Check.tsx, frontend/src/components/table/InterpreterDirectoryTable.tsx, frontend/src/components/table/InterpreterName.tsx, frontend/src/components/table/InterpreterSearchTable.tsx, frontend/src/constants/interfaces.ts, frontend/src/contexts/SearchContext.ts, frontend/src/util/locationFetch.ts, frontend/src/util/tableHelpers.tsx, frontend/src/views/CreateBooking.tsx
- Fix bug:  showing default "location value" when edit booking.
- Fix bug: limit 32 check disappeared abnormally.
- [sorting location](https://justice.gov.bc.ca/jira/browse/CSBISS-108):
- [refactor locationAutoComplete component](https://justice.gov.bc.ca/jira/browse/CSBISS-107)
=> Fix booking location

api/src/app.module.ts, api/src/booking/entities/booking.entity.ts, api/src/booking/ro/booking.ro.ts, api/src/event/entities/booking-event.entity.ts, api/src/event/entities/event.entity.ts, api/src/event/entities/interpreter-event.entity.ts, api/src/event/event.module.ts, api/src/event/event.service.spec.ts, api/src/event/event.service.ts, api/src/event/ro/event.ro.ts, api/src/interpreter/entities/interpreter.entity.ts, api/src/interpreter/ro/interpreter.ro.ts, api/src/migrations/1619727566425-CreateEventEntity.ts
PRing this first leg of work to avoid a huge PR later
- event entities +, RO
- updates to booking and interpreter ROs
=> Csbiss 61 changelog

api/src/app.module.ts, api/src/booking/booking.controller.ts, api/src/booking/booking.module.ts, api/src/booking/booking.service.ts, api/src/event/entities/booking-event.entity.ts, api/src/event/entities/event.entity.ts, api/src/event/entities/interpreter-event.entity.ts, api/src/event/event.service.ts, api/src/interpreter/interpreter.controller.ts, api/src/interpreter/interpreter.service.ts, frontend/src/components/Buttons.tsx, frontend/src/components/ChangeLog.tsx, frontend/src/components/form/EditBookingModal.tsx, frontend/src/components/reusable/Tag.tsx, frontend/src/components/table/DateTimeCell.tsx, frontend/src/components/table/InterpreterDirectoryTable.tsx, frontend/src/components/table/InterpreterSearchTable.tsx, frontend/src/constants/interfaces.ts, frontend/src/css/App.css, frontend/src/util/tableHelpers.tsx
This work builds off a merged PR and the `user` branch so it currently conflicts with `user` which has not rebase dev since that PR.
I'm opening for now so we can see where things are at.
PR covers the FE work to show updates for interpreters as well as the scaffolding for showing updates to bookings on the update bookings modal. It also corrects a number of errors on the API side such that events now function end to end.
NB: a migration will be needed to attach users to booking-event entities.
=> Csbiss 61 client

frontend/src/components/form/inputs/Autocomplete.tsx, frontend/src/components/form/inputs/Booking.tsx, frontend/src/components/form/schemas/booking.schema.ts
- fix the language X error.
- fix the "reason code" max limit 6
=> fix the fe error

api/src/booking/booking.service.ts, api/src/utils/index.ts, frontend/src/components/form/inputs/Autocomplete.tsx, frontend/src/components/form/inputs/Booking.tsx, frontend/src/components/form/schemas/booking.schema.ts
- add location data to Excel ADM 322.
=> Add new values to ADM322

api/src/common/constant.ts, api/src/language/__test__/language.e2e-spec.ts, api/src/language/language.controller.ts, api/src/language/language.service.ts, frontend/src/components/form/BookingModal.tsx, frontend/src/components/form/BookingsSearch.tsx, frontend/src/components/form/DirectorySearch.tsx, frontend/src/components/form/InterpreterSearch.tsx, frontend/src/components/form/inputs/AutocompleteLanguage.tsx, frontend/src/components/form/inputs/Booking.tsx, frontend/src/util/apiHelper.ts
------
1. Create single source of truth for all language drop down
2. Create api end point to fetch all languages names in sorted orders
3. Create one auto complete component to handle language drop down for all pages
----
=> [api][frontend] Fix Language defect

.docker/keycloak/test-realm.json, README.md, api/src/common/interceptors/user.interceptors.ts, api/src/common/interface/user.interface.ts, api/src/migrations/1620320684276-AddColumnUser.ts, api/src/user/entities/user.entity.ts, api/src/user/ro/user.ro.ts
- add GU_ID to userEntity
- add new migration to add GU_ID to user table
- rename a little bit on user.interceptor
=> [api] Add GuID

frontend/src/components/form/BookingsSearch.tsx, frontend/src/components/form/inputs/AutoCompleteField.tsx, frontend/src/util/apiHelper.ts
- showing default user location;
- `Get /booking` with default user location
- Add notification alert when save the user default location.
The reason of the bug:  material-ui component`Autocomplete`, can't set async value to `defaultValue` props.
=> [frontend] fix bug: default user location;

api/src/booking/booking-date.service.ts, api/src/booking/booking.controller.ts, api/src/utils/index.ts, frontend/src/components/table/BookingsTable.tsx
- update booking date correctly.
- small frontend bug: check date length > 0
=> [api][bug] Booking date unnecessary update

frontend/src/components/form/inputs/Booking.tsx, frontend/src/components/form/schemas/booking.schema.ts, frontend/src/components/table/InterpreterSearchTable.tsx, frontend/src/constants/booking.ts, frontend/src/views/CreateBooking.tsx
- ![image](https://user-images.githubusercontent.com/46575401/117869136-48e41600-b24f-11eb-8b12-dc0fe14cd644.png)
- ![image](https://user-images.githubusercontent.com/46575401/117869154-4da8ca00-b24f-11eb-90f7-2e86d2ac70c8.png)
=> [frontend] CS-102: requestedBy, interpretFor dropdown; CS-96: copy email

api/src/booking/entities/booking.entity.ts, api/src/utils/index.ts, frontend/src/components/table/BookingsTable.tsx, frontend/src/components/table/InterpreterSearchTable.tsx, frontend/src/css/App.css, frontend/src/util/sort.ts
Will build on this work with regards showing dates on the bookings table client side in next ticket.
=> Csbiss 114 sort bookings table

api/src/database/factories/Interpreter.factory.ts, api/src/database/seeds/2-create-interpreter.seed.ts, api/src/interpreter/entities/interpreter.entity.ts, api/src/interpreter/interpreter.service.ts, frontend/src/components/form/inputs/Interpreter.tsx
------
1. Fix interpreter create with crc date field assignment
2. Create hook to interpreter after load to populate value
:
=> [api][frontend][CSBISSS-#111] Fix CRC date field population issue

frontend/src/components/table/BookingsTable.tsx, frontend/src/components/table/DateTimeCell.tsx
=> show number of appearances, first and last date on bookings table

frontend/src/components/table/BookingsTable.tsx, frontend/src/components/table/DateTimeCell.tsx, frontend/src/util/sort.ts
@jerryfreshworks any ideas for how we can assign a type to row in our tables? I think we have to use generics in the `tables/Base` component
=> Csbiss 124 booking date info

api/src/interpreter/dto/create-interpreter.dto.ts, frontend/src/components/form/inputs/Interpreter.tsx, frontend/src/components/form/schemas/interpreter.schema.ts, frontend/src/components/table/InterpreterDirectoryTable.tsx, frontend/src/components/table/InterpreterSearchTable.tsx
- add `siteCode` related to frontend;
- "Search Interpreter" table
- "Interpreter" table
- Edit/Create Modal ( with yup check, 001;011;111;)
(Regex: https://stackoverflow.com/questions/15532634/regular-expression-for-3-digits-having-leading-zeros)
- add `siteCode` to backend dto.
- add regex to validation too.
=> [frontend][api] add siteCode to frontend; add siteCode to create.dto;

frontend/src/components/table/Base.tsx, frontend/src/components/table/BookingsTable.tsx
I test locally, working fine. And didn't affect other files using BaseTable, no matter you add the type or not.
=> add generic to BaseTable

api/src/booking/booking.service.ts, api/src/booking/dto/create-booking.dto.ts, api/src/booking/entities/booking.entity.ts, api/src/booking/ro/booking.ro.ts, api/src/migrations/1621292615427-AddColumnMOABooking.ts, frontend/src/components/form/inputs/Booking.tsx, frontend/src/components/form/schemas/booking.schema.ts, frontend/src/constants/booking.ts, frontend/src/constants/interfaces.ts
- Add `methodOfAppearance` to dto, ro, entity.
- Add `methodOfAppearance` dropdown to FE, create/edit booking;
- Add `methodOfAppearance` to Adm-322;
=> [api][frontend] CS-120 Add `Method of Appearance`

api/package-lock.json, api/package.json, api/src/booking/booking.service.ts, frontend/src/components/form/BookingsSearch.tsx, frontend/src/components/form/EditBookingModal.tsx, frontend/src/components/table/Status.tsx, frontend/src/constants/interfaces.ts, frontend/src/contexts/BookingSearchContext.ts, frontend/src/views/Booking.tsx
- Booking Status Color fixed: 
- Keep search booking criteria with context
=> [api][frontend] status color && booking search with criteria

api/src/booking/booking.controller.ts, api/src/booking/booking.module.ts, api/src/booking/booking.service.ts, api/src/distance/distance.service.ts, api/src/utils/index.ts
- add finance; 
- fix intp name; 
- add interpretFor and RequestedBy
=> [api] ADM-322 related tickets

api/src/interpreter/interpreter.service.ts, frontend/src/components/calendar/DirectoryCalendar.tsx, frontend/src/components/calendar/MoreDetails.tsx, frontend/src/components/table/BookingButton.tsx, frontend/src/components/table/InterpreterSearchTable.tsx, frontend/src/constants/interfaces.ts, frontend/src/util/tableHelpers.tsx, frontend/src/views/CreateBooking.tsx
https://justice.gov.bc.ca/jira/browse/CSBISS-130
=> 130 int availability

frontend/src/hooks/useError.ts
-  when error is null, return;
=> [frontend] bug fix: error msg 

api/src/booking/booking.service.ts, api/src/utils/index.ts
=> [api][adm-322] add rate; and fix distance wrong column

.docker/mock-justice-proxy/httpd.conf, devops/Makefile, docker-compose.dev.yml, frontend/src/index.tsx, frontend/src/views/login.tsx
Fixed an issue with the API connection and the router
=> Tweaks to the proxy code

api/api/repository/access_request_transactions.py, api/api/repository/adm_transactions.py, api/api/routers/adm_router.py, api/api/schemas/booking_schema.py, api/core/config.py, jenkins/config.groovy, web/src/components/tabs/components/AdmForms/AdmCalculations/PaymentCalculation.ts, web/src/components/tabs/components/AdmForms/AdmComponents/AdmOfficeUseOnly.vue, web/src/components/tabs/components/AdmForms/AdmComponents/AdmSentFormInfo.vue, web/src/components/tabs/components/AdmForms/AdmComponents/AdmSentInvoiceInfo.vue, web/src/components/tabs/components/AdmForms/AdmComponents/ButtonBar.vue, web/src/components/tabs/components/AdmForms/AdmComponents/SentEmailContent.vue, web/src/components/tabs/components/AdmForms/AdmForms.vue, web/src/components/tabs/components/AdmForms/pdf/Authorizations.vue, web/src/components/tabs/components/AdmForms/pdf/CancellationInfo.vue, web/src/components/tabs/components/AdmForms/pdf/OfficeUseOnly.vue, web/src/types/Bookings/json/index.ts
CSBISS-343: Adding functionality to send the generated form,
CSBISS-345: Add functionality to send the generated invoice
=> CSBISS-343, CSBISS-345

web/package-lock.json
Reverts bcgov/court-interpreter-scheduling#344
=> Revert "Bump @babel/traverse from 7.16.7 to 7.23.9 in /web"

web/src/components/tabs/components/BookingEnums.ts, web/src/components/tabs/components/CreateBookingModal/InterpreterBookingFields.vue, web/src/components/tabs/components/DateComponents/TimePicker/DefaultTimeSelector.vue, web/src/components/tabs/components/EditBookingModal/EditBookingFields.vue, web/src/components/tabs/components/EditBookingModal/EditBookingModal.vue
CSBISS-422: Update label of the morning session time range
CSBISS-434: Add new reason codes
CSBISS-433: Resolve logout issue
=> CSBISS-420: Add new cancellation reason options

api/alembic/versions/e15dc8fa858a_added_interpreter_language_table.py, docker/manage
- use node12 for running vue app
- fix seed data processing in interpreter_language file
=> Fix issues for running app locally

api/api/repository/search_interpreter_transactions.py, api/api/routers/interpreter_router.py, api/api/schemas/interpreter_search_schema.py, api/api/schemas/pagination_schema.py, web/package-lock.json, web/src/components/tabs/SearchInterpretersPage.vue, web/src/components/tabs/components/SearchInterpretersCalendarTable.vue, web/src/components/tabs/components/SearchInterpretersTable.vue
- add pagination schema
- add offset and limit to the query to get only the first few paginated data
- Change frontend to query every time pagination or search changed
=> CSBISS-471: Fix performance issue with loading large amount of interpreters

web/src/components/tabs/components/SearchInterpretersTable.vue
CSBISS-472: Show correct information in interpreter search table row details
=> CSBISS-472: Show correct information in interpreter search table row details

api/api/repository/search_interpreter_transactions.py, api/api/routers/interpreter_router.py, api/api/schemas/interpreter_search_schema.py, web/src/components/tabs/Admin/Directory.vue, web/src/components/tabs/SearchInterpretersPage.vue, web/src/components/tabs/components/SearchInterpretersCalendarTable.vue, web/src/components/tabs/components/SearchInterpretersTable.vue
- check the preformace of search query to get court distance
- Fix copy emails on this page to clipboard
- Fix concatinate email strings using `;` instead of `,`
=> CSBISS-471: Fix interpreter directory search issue

api/jc_interface/jc_update_courts.py, web/src/components/tabs/components/CreateBookingModal/InterpreterBookingModal.vue
still need to keep eFiling server as a reference for court addresses
=> remove eFiling LocationCode condition from update_courts_info_in_db()
